## Input file: cuda with newton flux
## NOTE: if number of voxels is more than 2 bilions, change the TAGINT format to int64 in pointers.h

partition 1 1 1 
num_conn_max 10 # maximum number of bond connections
strategy OMP

## special for cuda
newton_flux yes

timestep 0.0005 # day
nevery 10 # nevery steps for bond connections
box -5.0e4 5.0e4  -5.0e4 5.0e4  -5.0e4 5.0e4 # xlo xhi  ylo yhi  zlo zhi (um)

voxel_size 1.0e3 # um (Note: minimum voxel_size is 100 um in order to include 70 neurons in itself.)

## parameters
parameters diff_sAb 2.0e7 # um2/day
parameters kp 2.6e1 # 1/uM . 1/day
parameters kn 1.7e-1 # 1/uM . 1/day
parameters ds 5.3e-9 # mL/day
parameters df 1.8e-10 # mL/day
parameters es 1.9 # 1/day
parameters diff_mic 2.0e4 # um2/day
parameters sens_s 2.2e3 # um/day per uM/um
parameters sens_f 2.2e4 # um/day per uM/um
parameters Ha 1.0e5 # Michaelis-Menten constant for astrogliosis (uM/mL)
parameters ka 0.01 # astroglyiosis rate (1/day)
parameters diff_tau 9.2e6 # um2/day
parameters dnt 1.0e-9 # neuronal death rate due to tau tangles (1/day . 1/uM)
parameters ktau 4.1e1 # rate of tangle formation (1/day)
parameters kphi 1.0e-3 # phosphorylation rate of tau proteins due to F and N (mL/day)
parameters ephi 1.9 # phosphorylated-tau discharge (1/day)

# circadian rhythm parameters
# Note: don't set "cir" parameter when you use circadian rhythm
parameters C_cir 2.0e-11 # neuronal Abeta secretion (mol/day/neuron)
parameters c_cir 0 # dimensionless amplitude
parameters tau_cir 1.0 # period (day)

parameters neu 0.0 # 1/mL
parameters mic 1.1e7 # 1/mL
parameters sAb 0.0 # uM
parameters fAb 0.0 # uM
parameters ast 0.0 # astrogliosis
parameters phr 0.0 # uM
parameters tau 0.0 # uM

#region sphere 0.0 0.0 0.0 4.99e4 out type -1
#region sphere 0.0 0.0 0.0 4.99e4 in type 1
#region sphere 0.0 0.0 0.0 1.0e3 in mic 1.0e6

## input mri files
#read_mri restart restart.nii 0.0 1.0
#read_mri all mni152_2009bet.nii 0.5 1.0e8
#read_mri csf csf.nii 0.0 1.0
read_mri wm ../base/wm.nii 0.3 3.1e6
read_mri gm ../base/gm.nii 0.25 3.1e7
read_mri csf ../base/csf.nii 0.1 1.0
read_mri group ../base/voi.nii 0 0

read_mri rgb ../base/rgb.nii 0 255

#balance y 20

## outputs
dump mri 200 dump. mic neu sAb fAb ast phr tau type group
statistics 200 stat.dat

log 20
run 200
setup
